### ISSUE TITLE
Consider using uf2conv-rs

### ISSUE THREAD

**Issue by sajattack** [everett1992/digital_die#3]
Ohai there. I took a gander at your repo and noticed you're using python to do your uf2 conversion in an otherwise all Rust project. Lucky for you, I have written a Rust tool to do this @ https://github.com/sajattack/uf2conv-rs It has similar syntax to uf2conv.py. 
`uf2conv-rs inputfile -o outputfile` should suffice in your case.

**Comment by everett1992** [comment]
Does cargo have an option to install rust tools and track them as dependencies? `cargo install` installs to `$HOME/.cargo`. It doesn't record the dependency in Cargo.toml. If I added it to dependencies in Cargo.toml uf2conv-rs would be compiled for arm instead of my build host architecture.

**Comment by sajattack** [comment]
I don't think so. You could use a git submodule maybe or just put the binary in your repo. I mean, previously you just had the python script in your repo.

**Comment by everett1992** [comment]
I already use `cargo install` for objcopy, so another similar dependency isn't a big deal. I'll switch to `uf2conf-rs`.

I'm pretty new to rust and I'm looking at the docs for [build-dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) and [build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) for the first time. It looks like the build script will run before rustc, but not after, so we couldn't use it to call generate the uf2 binary.

Some discussion here
https://github.com/rust-lang/cargo/issues/545

**Comment by sajattack** [comment]
Yes that's correct.

**Comment by everett1992** [comment]
switched to uf2conv-rs, thank you
